# hyprmarker configuration file
# Location: ~/.config/hyprmarker/config.toml
#
# All settings are optional. If not specified, defaults will be used.
# Delete this file to reset to defaults.

# ═══════════════════════════════════════════════════════════════════════════════
# DRAWING SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

[drawing]
# Default pen color
# Options: "red", "green", "blue", "yellow", "orange", "pink", "white", "black"
# Or RGB array: [255, 0, 0]
default_color = "red"

# Default pen thickness in pixels (1.0 - 20.0)
default_thickness = 3.0

# Default font size for text mode (8.0 - 72.0)
default_font_size = 32.0

# ───────────────────────────────────────────────────────────────────────────────
# Font Configuration (Pango-based text rendering)
# ───────────────────────────────────────────────────────────────────────────────

# Font family name for text rendering
# Install fonts system-wide and reference by family name
# Examples to try:
#   font_family = "Sans"              # Default sans-serif
#   font_family = "Monospace"         # Fixed-width font
#   font_family = "Serif"             # Serif font
#   font_family = "JetBrains Mono"    # If installed
#   font_family = "Fira Code"         # If installed
#   font_family = "Maple Mono NF"     # If installed
#   font_family = "DejaVu Sans"       # Common on Linux
#   font_family = "Liberation Sans"   # Common on Linux
#   font_family = "Noto Sans"         # Google Noto fonts
# Falls back to "Sans" if the specified font is not available
font_family = "Sans"

# Font weight: "normal", "bold", "light", "ultralight", "heavy", "ultrabold"
# Or numeric: 100-900 (400=normal, 700=bold)
# Try different weights:
#   font_weight = "normal"    # Regular weight
#   font_weight = "bold"      # Bold (default, best visibility)
#   font_weight = "light"     # Light weight
#   font_weight = "600"       # Semi-bold (numeric)
font_weight = "bold"

# Font style: "normal", "italic", "oblique"
# Try different styles:
#   font_style = "normal"     # Standard upright text
#   font_style = "italic"     # Italic/cursive
#   font_style = "oblique"    # Slanted text
font_style = "normal"

# Enable semi-transparent background box behind text for better contrast
# Set to true if you find text hard to read against complex backgrounds
# Default: false (no background, cleaner look with just stroke outline)
text_background_enabled = false

# ═══════════════════════════════════════════════════════════════════════════════
# ARROW SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

[arrow]
# Arrowhead length in pixels
length = 20.0

# Arrowhead angle in degrees (15-60)
# 30 degrees gives a nice balanced arrow
angle_degrees = 30.0

# ═══════════════════════════════════════════════════════════════════════════════
# PERFORMANCE SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

[performance]
# Number of buffers for rendering (2, 3, or 4)
# 2 = double buffering (low memory)
# 3 = triple buffering (recommended, smooth)
# 4 = quad buffering (ultra-smooth on high refresh displays)
buffer_count = 3

# Enable vsync frame synchronization
# Prevents tearing and limits rendering to display refresh rate
enable_vsync = true

# ═══════════════════════════════════════════════════════════════════════════════
# UI SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

[ui]
# Show status bar with current color/thickness/tool
show_status_bar = true

# Status bar position
# Options: "top-left", "top-right", "bottom-left", "bottom-right"
status_bar_position = "bottom-left"

# ───────────────────────────────────────────────────────────────────────────────
# Status Bar Styling
# ───────────────────────────────────────────────────────────────────────────────

[ui.status_bar_style]
# Font size for status bar text
font_size = 21.0

# Padding around status bar text
padding = 15.0

# Background color [R, G, B, A] (0.0-1.0 range)
# Default: semi-transparent black (85% opaque for visibility)
bg_color = [0.0, 0.0, 0.0, 0.85]

# Text color [R, G, B, A] (0.0-1.0 range)
# Default: white
text_color = [1.0, 1.0, 1.0, 1.0]

# Color indicator dot radius
dot_radius = 6.0

# ───────────────────────────────────────────────────────────────────────────────
# Help Overlay Styling (Press F10 to toggle)
# ───────────────────────────────────────────────────────────────────────────────

[ui.help_overlay_style]
# Font size for help overlay text
font_size = 16.0

# Line height for help text
line_height = 22.0

# Padding around help box
padding = 20.0

# Background color [R, G, B, A] (0.0-1.0 range)
# Default: semi-transparent black (darker than status bar)
bg_color = [0.0, 0.0, 0.0, 0.85]

# Border color [R, G, B, A] (0.0-1.0 range)
# Default: light blue
border_color = [0.3, 0.6, 1.0, 0.9]

# Border line width
border_width = 2.0

# Text color [R, G, B, A] (0.0-1.0 range)
# Default: white
text_color = [1.0, 1.0, 1.0, 1.0]
